In [1]:
import numpy as np


In [3]:
an_array =  np.array([1,1,2,3,5,8,13])


In [4]:
an_array.shape

(7,)

In [12]:
an_array.append[10]

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
an_array

array([1, 1, 2, 3, 5, 8, 9])

In [18]:
another = np.array([[1,1,2,3,5,8,13],[3,33,333,0,0,0,0]])

In [19]:
another.shape

(2, 7)

In [21]:
another[1,1]

33

In [22]:
a = np.zeros((5,5))

In [23]:
a


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
b= np.ones((6,6))

In [25]:
b

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
c = np.eye(4,4)

In [27]:
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
d = np.full((7,7),9)
d

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [36]:
rand = np.random.random((6,6))
rand

array([[0.68024741, 0.42673636, 0.18383804, 0.9523674 , 0.69705206,
        0.58055446],
       [0.82419769, 0.01095892, 0.36828488, 0.14334555, 0.53243856,
        0.73253745],
       [0.55204792, 0.44902488, 0.32392341, 0.77070332, 0.87298409,
        0.8491666 ],
       [0.41159815, 0.56859112, 0.10792439, 0.11035007, 0.53619306,
        0.51063694],
       [0.91895302, 0.78105144, 0.14380198, 0.03608626, 0.4065397 ,
        0.17680621],
       [0.39660572, 0.19680235, 0.94119504, 0.33747567, 0.36591016,
        0.28620716]])

In [40]:
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [38]:
indexed_slice = an_array[1,:]
indexed_slice

array([21, 22, 23, 24])

In [39]:
slic = an_array[1:2, :]
slic

array([[21, 22, 23, 24]])

In [43]:
row_indices = np.array([0,1,2,0])
column_indices = np.arange(4)

In [46]:
an_array[row_indices,column_indices] += 1000
an_array

array([[1011,   12,   13, 1014],
       [  21, 1022,   23,   24],
       [  31,   32, 1033,   34]])

In [48]:
#Boolean
an_array[an_array > 1000] -=1000
an_array

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])