In [1]:
from scipy import sparse as sp
import pandas as pd
import numpy as np

In [36]:
from numpy import dot, source
source(dot)

Not available for this object.


In [5]:
df = pd.DataFrame(np.random.randint(0,2,size=(5, 4)))

In [6]:
df


0  1  2  3
0  1  0  0  1
1  1  1  0  0
2  0  1  1  0
3  1  0  1  0
4  0  1  1  1

In [42]:
Z = zip(df,df)


In [43]:
print(tuple(Z))

((0, 0), (1, 1), (2, 2), (3, 3))


In [13]:
left = df.values
left


array([[1, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 0],
       [1, 0, 1, 0],
       [0, 1, 1, 1]])

In [14]:
right = np.asarray(df)
right

array([[1, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 0],
       [1, 0, 1, 0],
       [0, 1, 1, 1]])

In [26]:
def dot(v1,v2):
    return sum(x*y for x,y in zip(v1,v2))

In [30]:
dot(left[0],right[1])

1

In [31]:
dot(left,right)

array([3, 3, 3, 2])

In [29]:
np.dot(left,right)

ValueError: shapes (5,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)

In [20]:
np.lookfor('dot')

Search results for 'dot'
------------------------
numpy.dot
    Dot product of two arrays. Specifically,
numpy.vdot
    Return the dot product of two vectors.
numpy.tensordot
    Compute tensor dot product along specified axes for arrays >= 1-D.
numpy.ma.dot
    Return the dot product of two arrays.
numpy.chararray.dot
    Dot product of two arrays.
numpy.linalg.multi_dot
    Compute the dot product of two or more arrays in a single function call,
numpy.linalg.tensorinv
    Compute the 'inverse' of an N-dimensional array.
numpy.ma.MaskedArray.dot
    Masked dot product of two arrays. Note that `out` and `strict` are
numpy.cov
    Estimate a covariance matrix, given data and weights.
numpy.inner
    Inner product of two arrays.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.matmul
    Matrix product of two arrays.
numpy.polyint
    Return an antiderivative (indefinite integral) of a polynomial.
numpy.einsum_path
    Evaluates the lowest cost contra

In [7]:
print(df)

   0  1  2  3
0  1  0  0  1
1  1  1  0  0
2  0  1  1  0
3  1  0  1  0
4  0  1  1  1


In [8]:
a = df

In [9]:
b = df.T
b

0  1  2  3  4
0  1  1  0  1  0
1  0  1  1  0  1
2  0  0  1  1  1
3  1  0  0  0  1

In [10]:
a.dot(b)

0  1  2  3  4
0  2  1  0  1  1
1  1  2  1  1  1
2  0  1  2  1  2
3  1  1  1  2  1
4  1  1  2  1  3

In [39]:
b.dot(a)

0  1  2  3
0  3  0  2  1
1  0  1  0  0
2  2  0  3  2
3  1  0  2  2

In [43]:
print(df.T.dot(df))

   0  1  2  3
0  3  0  2  1
1  0  1  0  0
2  2  0  3  2
3  1  0  2  2
